all: restaurant.out supplier.out customer.out

restaurant.out: *.c
	gcc restaurant_owner.c -o restaurant.out
supplier.out : *.c
	gcc supplier.c -o supplier.out
customer.out: *.c
	gcc customer.c -o customer.out
clean:
	rm *.out